# Copyright (c) 2026 Vitaly Chipounov
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Generates version.h at the solution root. The header embeds the driver
# version and the current git commit hash into the version resources of the
# driver and the test app. The prebuild project runs this script before every
# build; the other projects depend on prebuild so the header is generated
# exactly once, before any of them compiles.

$Major = 1
$Minor = 0
$Build = 0
$Revision = 0

$SolutionDir = Split-Path -Parent $PSScriptRoot
$OutputFile = Join-Path $SolutionDir "version.h"

$Hash = ""
$GitError = ""
try {
    $GitOutput = & git -C $SolutionDir rev-parse --short HEAD 2>&1
    if ($LASTEXITCODE -eq 0) {
        $Hash = "$GitOutput"
    } else {
        $GitError = "$GitOutput"
    }
} catch {
    $GitError = $_.Exception.Message
}

# A missing git or a checkout without .git must not break the build.
if ([string]::IsNullOrWhiteSpace($Hash)) {
    Write-Warning "generate-version.ps1: git hash unavailable, using 'unknown': $GitError"
    $Hash = "unknown"
} else {
    $Hash = $Hash.Trim()
}

$VersionString = "$Major.$Minor.$Build.$Revision-$Hash"

$Content = @"
// Generated by prebuild/generate-version.ps1. Do not edit.

#define PHOTONIC_VERSION_MAJOR $Major
#define PHOTONIC_VERSION_MINOR $Minor
#define PHOTONIC_VERSION_BUILD $Build
#define PHOTONIC_VERSION_REVISION $Revision

#define PHOTONIC_VERSION_STRING "$VersionString"
"@

# The here-string above inherits the line endings of this script file, which
# are LF when the repository is checked out on Linux. Normalize to CRLF so
# version.h has consistent Windows line endings.
$Content = $Content -replace "`r?`n", "`r`n"

# Rewrite the header only when the content changed, so an unchanged hash keeps
# the timestamp stable and incremental builds do not recompile the resources.
# The read must tolerate a missing file even when Test-Path says it exists:
# on a network share, a stale SMB directory cache can report a deleted file
# as still present.
$Existing = $null
if (Test-Path $OutputFile) {
    $Existing = Get-Content $OutputFile -Raw -ErrorAction SilentlyContinue
}

if (($null -ne $Existing) -and ($Existing.TrimEnd() -eq $Content)) {
    Write-Host "version.h is up to date: $VersionString"
} else {
    try {
        Set-Content -Path $OutputFile -Value $Content -Encoding Ascii -ErrorAction Stop
    } catch {
        Write-Error "generate-version.ps1: cannot write ${OutputFile}: $_"
        exit 1
    }
    Write-Host "Generated version.h: $VersionString"
}
